version: "3.7"

services:
  postgres:
    image: "postgres:11"
    environment:
      - POSTGRES_USER=postgresBlog
      - POSTGRES_DB=postgresBlog
      - POSTGRES_PASSWORD=postgres_password
    ports:
      - "5432:5432"
  pgadmin:
    image: "dpage/pgadmin4"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@blog.com
      - PGADMIN_DEFAULT_PASSWORD=admin12345
    ports:
      - "5000:80"
    logging:
      driver: none
  frontend:
    build:
      context: ./blog-frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./blog-frontend:/app
    ports:
      - "3000:3000"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./blog-server
    volumes:
      - /app/node_modules
      - ./blog-server:/app
    ports:
      - "8000:3000"
    environment:
      - NODE_ENV=development
      - PG_USERNAME=postgresBlog
      - PG_HOST=postgresBlog
      - PG_DATABASE=postgresBlog
      - PG_PASSWORD=postgres_password
      - PG_PORT=5432
      - JWT_SECRET=IL0veCoding
